<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-HHFIH5D1" ignored="0" name="Test" tests="6" failures="1" timestamp="30 Apr 2020 10:51:36 GMT" time="7.129" errors="0">
  <testcase name="feature" time="1.651" classname="cucumber.api.testng.AbstractTestNGCucumberTests"/>
  <testcase name="feature" time="0.457" classname="cucumber.api.testng.AbstractTestNGCucumberTests"/>
  <testcase name="feature" time="0.32" classname="cucumber.api.testng.AbstractTestNGCucumberTests"/>
  <testcase name="feature" time="1.508" classname="cucumber.api.testng.AbstractTestNGCucumberTests">
    <failure type="cucumber.runtime.CucumberException" message="java.lang.AssertionError: expected [83222441] but found [54346799]">
      <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: expected [83222441] but found [54346799]
at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
Caused by: java.lang.AssertionError: expected [83222441] but found [54346799]
at com.servicenow.githubapitest.stepdefinitions.SearchLangRepos.i_validate_the_details_of_the_first_repository_from_response(SearchLangRepos.java:64)
at âœ½.And I validate the details of the first repository from response(SearchLangRepos.feature:7)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- feature -->
  <testcase name="feature" time="1.458" classname="cucumber.api.testng.AbstractTestNGCucumberTests"/>
  <testcase name="feature" time="1.362" classname="cucumber.api.testng.AbstractTestNGCucumberTests"/>
</testsuite> <!-- Test -->
